<h2>Listando Membros</h2>
<p>
	<a href="<?php echo $this->url(array('action' => 'adicionar')); ?>" class="button_top">Novo Membro</a>
</p>
<table class="grid">
	<thead>
		<tr>
			<th scope="col">Nome</th>
			<th scope="col">Telefone</th>
			<th scope="col">Editar</th>
			<th scope="col">Excluir</th>
		</tr>
	</thead>
	<tbody>
	<?php if ( sizeof($this->membros) == 0 ): ?>
		<tr>
			<td colspan="4">Nenhum registro encontrado.</td>
		</tr>
	<?php else: ?>
	<?php foreach ($this->membros as $membro): ?>
		<tr>
			<td><a href="<?php echo $this->url(array('action' => 'visualizar', 'id' => $membro->getId())); ?>"><?php echo $membro->getNome(); ?></a></td>
			<td><a href="<?php echo $this->url(array('action' => 'visualizar', 'id' => $membro->getId())); ?>"><?php echo $membro->getTelefone(); ?></a></td>
			<td><a href="<?php echo $this->url(array('action' => 'editar', 'id' => $membro->getId())); ?>">Editar</a></td>
			<td><a href="<?php echo $this->url(array('action' => 'deletar', 'id' => $membro->getId())); ?>" onclick="return deletar(this.href);">Excluir</a></td>
		</tr>
	<?php endforeach; ?>
	<?php endif; ?>
	</tbody>
</table>