<h2>Listando Livros</h2>
<p>
	<a href="<?php echo $this->url(array('action' => 'adicionar')); ?>" class="button_top">Novo Livro</a>
</p>
<table class="grid">
	<thead>
		<tr>
			<th scope="col">ISBN</th>
			<th scope="col">T&iacute;tulo</th>
			<th scope="col">Editora</th>
			<th scope="col">Autor</th>
			<th scope="col">Editar</th>
			<th scope="col">Excluir</th>
		</tr>
	</thead>
	<tbody>
	<?php if ( sizeof($this->livros) == 0 ): ?>
		<tr>
			<td colspan="6">Nenhum registro encontrado.</td>
		</tr>
	<?php else: ?>
	<?php foreach ($this->livros as $livro): ?>
		<tr>
			<td><a href="<?php echo $this->url(array('action' => 'visualizar', 'isbn' => $livro->getIsbn())); ?>"><?php echo $livro->getIsbn(); ?></a></td>
			<td><a href="<?php echo $this->url(array('action' => 'visualizar', 'isbn' => $livro->getIsbn())); ?>"><?php echo $livro->getTitulo(); ?></a></td>
			<td><?php echo $livro->getEditora()->getNome(); ?></td>
			<td><?php echo $livro->getAutor()->getNome(); ?></td>
			<td><a href="<?php echo $this->url(array('action' => 'editar', 'isbn' => $livro->getIsbn())); ?>">Editar</a></td>
			<td><a href="<?php echo $this->url(array('action' => 'deletar', 'isbn' => $livro->getIsbn())); ?>" onclick="return deletar(this.href);">Excluir</a></td>
		</tr>
	<?php endforeach; ?>
	<?php endif; ?>
	</tbody>
</table>