<h2>Listando Editoras</h2>
<p>
	<a href="<?php echo $this->url(array('action' => 'adicionar')); ?>" class="button_top">Nova Editora</a>
</p>
<table class="grid">
	<thead>
		<tr>
			<th scope="col">Nome</th>
			<th scope="col">Localiza&ccedil;&atilde;o</th>
			<th scope="col">Website</th>
			<th scope="col">Editar</th>
			<th scope="col">Excluir</th>
		</tr>
	</thead>
	<tbody>
	<?php if ( sizeof($this->editoras) == 0 ): ?>
		<tr>
			<td colspan="5">Nenhum registro encontrado.</td>
		</tr>
	<?php else: ?>
	<?php foreach ($this->editoras as $editora): ?>
		<tr>
			<td><a href="<?php echo $this->url(array('action' => 'visualizar', 'id' => $editora->getId())); ?>"><?php echo $editora->getNome(); ?></a></td>
			<td><a href="<?php echo $this->url(array('action' => 'visualizar', 'id' => $editora->getId())); ?>"><?php echo $editora->getLocalizacao(); ?></a></td>
			<td><?php echo $editora->getWebsite(); ?></td>
			<td><a href="<?php echo $this->url(array('action' => 'editar', 'id' => $editora->getId())); ?>">Editar</a></td>
			<td><a href="<?php echo $this->url(array('action' => 'deletar', 'id' => $editora->getId())); ?>" onclick="return deletar(this.href);">Excluir</a></td>
		</tr>
	<?php endforeach; ?>
	<?php endif; ?>
	</tbody>
</table>